In [8]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv("C:/Users/Natalia/OneDrive/Desktop/Datasets/survey_results_public.csv")
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [15]:
schema = pd.read_csv("C:/Users/Natalia/OneDrive/Desktop/Datasets/survey_results_schema.csv")
schema.head()

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

#### Скільки респондентів пройшли опитування?

In [22]:
df.ResponseId.nunique()

49123

#### Скільки респондентів відповіли на всі запитання?

In [16]:
questions_from_survey = df.columns
questions_from_schema = schema.qname
print(questions_from_survey)
print(questions_from_schema)

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=170)
0        TechEndorse_1
1        TechEndorse_2
2        TechEndorse_3
3        TechEndorse_4
4        TechEndorse_5
            ...
134    AIAgentObsWrite
135    AIAgentExternal
136    AIAgentExtWrite
137            AIHuman
138             AIOpen
Name: qname, Length: 139, dtype: object

In [21]:
both = set(questions_from_survey)&set(questions_from_schema)
print(both)

{'DatabaseHaveEntry', 'AIAgent_Uses', 'AIAgentObsWrite', 'TechOppose_2', 'TechOppose_15_TEXT', 'JobSatPoints_9', 'TechEndorse_8', 'ToolCountWork', 'PurchaseInfluence', 'SOVisitFreq', 'EmploymentAddl', 'JobSatPoints_5', 'LearnCodeChoose', 'SOComm', 'Country', 'AISelect', 'JobSatPoints_4', 'SOAccount', 'NewRole', 'CommPlatformWantEntr', 'DevEnvsChoice', 'TechOppose_1', 'AIOpen', 'JobSatPoints_7', 'TechOppose_15', 'LearnCode', 'TechEndorse_13_TEXT', 'AIThreat', 'AIExplain', 'YearsCode', 'DatabaseWantEntry', 'AIModelsHaveEntry', 'SO_Actions_15', 'SO_Dev_Content', 'JobSatPoints_16', 'AIModelsWantEntry', 'JobSat', 'JobSatPoints_15_TEXT', 'LearnCodeAI', 'WebframeHaveEntry', 'AIAcc', 'JobSatPoints_13', 'CompTotal', 'TechEndorse_13', 'LanguagesHaveEntry', 'SO_Actions_5', 'TechEndorse_1', 'SO_Actions_6', 'OrgSize', 'TechEndorse_5', 'MainBranch', 'WebframeChoice', 'TechOppose_11', 'SOFriction', 'AIFrustration', 'AIHuman', 'DevEnvWantEntry', 'AIAgents', 'TechEndorse_3', 'WebframeWantEntry', 'SOTagsWant Entry', 'JobSatPoints_6', 'Industry', 'AIAgentOrchestration', 'OfficeStackWantEntry', 'TechOppose_13', 'RemoteWork', 'LanguageChoice', 'TechEndorse_6', 'TechEndorseIntro', 'JobSatPoints_14', 'AIComplex', 'PlatformChoice', 'WorkExp', 'AILearnHow', 'Currency', 'SO_Actions_10', 'TechOppose_3', 'AIAgentKnowWrite', 'AIModelsChoice', 'AISent', 'AIAgentExtWrite', 'LanguagesWantEntry', 'SODuration', 'PlatformWantEntry', 'AIAgentObserveSecure', 'CommPlatformHaveEntr', 'DevEnvHaveEntry', 'TechEndorse_7', 'SO_Actions_16', 'Employment', 'AIAgentChange', 'AIAgentKnowledge', 'JobSatPoints_11', 'SO_Actions_7', 'TechEndorse_4', 'SO_Actions_15_TEXT', 'TechOppose_16', 'SO_Actions_9', 'JobSatPoints_8', 'OfficeStackHaveEntry', 'SOPartFreq', 'AIAgentExternal', 'EdLevel', 'AgentUsesGeneral', 'DevType', 'TechEndorse_9', 'PlatformHaveEntry', 'SOTagsHaveEntry', 'SO_Actions_4', 'SO_Actions_3', 'TechOppose_5', 'TechOppose_7', 'TechOppose_9', 'JobSatPoints_1', 'DatabaseChoice', 'JobSatPoints_15', 'ToolCountPersonal', 'AIAgentOrchWrite', 'JobSatPoints_10', 'SO_Actions_1', 'Age', 'ICorPM', 'TechEndorse_2'}

In [33]:
subset = df[list(both)]
respondents_all_answered = subset.dropna().shape[0]
print("Кількість респондентів, що відповіли на всі запитання:", respondents_all_answered)

Кількість респондентів, що відповіли на всі запитання: 0

#### Які значення мір центральної тенденції для досвіду (WorkExp) респондентів?

In [36]:
df["WorkExp"].agg(["mean", "median"])

mean      13.37081
median    10.00000
Name: WorkExp, dtype: float64

#### Скільки респондентів працює віддалено?

In [40]:
df["RemoteWork"].unique()

array(['Remote', 'Hybrid (some in-person, leans heavy to flexibility)',
       nan, 'In-person', 'Hybrid (some remote, leans heavy to in-person)',
       'Your choice (very flexible, you can come in when you want or just as needed)'],
      dtype=object)

In [39]:
remote_count = (df["RemoteWork"] == "Remote").sum()
print("Кількість респондентів, які працюють віддалено:", remote_count)

Кількість респондентів, які працюють віддалено: 10924

#### Який відсоток респондентів програмує на Python?

In [42]:
total =len(df)
python_count = df["LanguageHaveWorkedWith"].str.contains("Python", na=False).sum()
python_percent = python_count / total * 100

print("Кількість Python-програмістів:", python_count)
print("Відсоток респондентів, що програмують на Python:", python_percent)

Кількість Python-програмістів: 18444
Відсоток респондентів, що програмують на Python: 37.54656678134479

#### Скільки респондентів навчалося програмувати за допомогою онлайн курсів?

In [43]:
online_courses = df["LearnCode"].str.contains("Online Courses", na=False).sum()

print("Кількість респондентів, що навчалися за допомогою онлайн-курсів:", online_courses)

Кількість респондентів, що навчалися за допомогою онлайн-курсів: 10957

#### Серед респондентів що програмують на Python в групуванні по країнам, яка середня та медіанна сума компенсації (ConvertedCompYearly) в кожній країні?

In [44]:
python_df = df[df["LanguageHaveWorkedWith"].str.contains("Python", na=False)]
comp_stats = python_df.groupby("Country")["ConvertedCompYearly"].agg(["mean", "median"])
print(comp_stats)

                                               mean    median
Country
Afghanistan                            22328.666667    1000.0
Albania                                47217.600000   50000.0
Algeria                                20187.285714    7088.0
Andorra                               226103.500000  226103.5
Angola                                          NaN       NaN
...                                             ...       ...
Venezuela, Bolivarian Republic of...    9908.647059    3000.0
Viet Nam                              218837.166667    8254.0
Yemen                                  32929.500000   23672.0
Zambia                                  5424.250000    3206.0
Zimbabwe                               34000.000000   25500.0

[167 rows x 2 columns]

#### Які рівні освіти мають 5 респондентів з найбільшою компенсацією?

In [45]:
df["ConvertedCompYearly"] = pd.to_numeric(df["ConvertedCompYearly"], errors='coerce')
top5 = df.sort_values("ConvertedCompYearly", ascending=False).head(5)
top5[["ConvertedCompYearly", "EdLevel", "Country"]]

,ConvertedCompYearly,EdLevel,Country
34267,50000000.0,"Associate degree (A.A., A.S., etc.)",United States of America
28700,33552715.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Ukraine
43143,18387548.0,"Associate degree (A.A., A.S., etc.)",Poland
35353,15430267.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Iran, Islamic Republic of..."
45971,13921760.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Netherlands